*** Variable ***
${directory}   /home/robert/tau/TAU---basen/robotframework/figury
${error_args_text}    ERROR:nieprawidlowa_liczba_argumentow: Podales za duzo argumentow - podaj 3 lub 4 dlugosci bokow
${error_triangle_text}    ERROR:nieprawidlowa_figura: Z podanych bokow nie da się złożyć trójkąta
${error_quadrangle_text}    ERROR:nieprawidlowa_figura: Z podanych bokow nie da się złożyć czworokąt
${equilateral triangle_text}    trójkąt równoboczny
${isosceles_triangle_text}    trójkąt równoramienny
${multiarmed_triangle_text}    trójkąt różnoramienny
${square_text}    kwadrat
${rectangle_text}    prostokąt
${quadrangle_text}    czworobok